name: SpreadTheLove
version: 1.0
author: Numin
main: me.numin.love.Main
description: Spread the love!

commands:
  spreadthelove:
    usage: /<command>
    aliases: stl
    description: Shows you how to love.