name: SpreadTheLove
version: 1.0
author: Numin
main: me.numin.love.Main
description: Spread the love!

commands:
  spreadthelove:
    usage: /<command>
    aliases: stl
    description: Shows you how to love.
    
permissions:
  love.lovetrail:
    default: op
    description: Access to the lovetrail.
  love.hug:
    default: true
    description: Access to the huggies.
  love.kiss:
    default: true
    description: Access to the smoochies.
  love.gui:
    default: op
    description: Alternative to commands.